Repository Student-Labs-2023/BoilerPoint, pull requests merged in 2023-07, with the labels that each got.

#8 Features-C3-DatabaseFunc
  Database/DataUsers.py
  Database/__pycache__/DataUsers.cpython-310.pyc
  main.py
  repository/usersrepository.py
  src/models/__init__.py
  src/models/users.py
  src/repository/usersrepository.py
Labels: enhancement

#18 Features-A3-ReworkDatabaseInteraction
  GoogleSheets/Google_sheets.py
  buttons.py
  main.py
  src/__init__.py
  src/models/__init__.py
  src/models/users.py
  src/repository/SupabaseUserRepository.py
  src/repository/__init__.py
  src/repository/usersrepository.py
Labels: enhancement

#36 Features-B4-MakeRepoPatternInMain
  Database/DataUsers.py
  buttons.py
  main.py
  requirements.txt
  src/repository/SupabaseUserRepository.py
Labels: enhancement

#44 Features-A4-EditProfile
  buttons.py
  main.py
Labels: enhancement

#59 Documentation-A4
  Documentation/Docs/README.md
  Documentation/User guide/README.md
Labels: documentation

#61 Features-B4-GetInfoAboutUserInAdmin
  buttons.py
  main.py
Labels: enhancement

#66 Features-A5-EventScriptLeaderId
  leaderid_synchronizer/script.ts
Labels: enhancement

#67 Features-A5-ModularSystemForFunc
  funcs.py
  main.py
Labels: enhancement

#68 Features-B5-AddNamingPromo
  buttons.py
  codegen.py
  main.py
Labels: duplicate

#69 Features-C5-DelZeroLastPromo
  main.py
Labels: enhancement

#72 Features-A5-AddEventMakerPanel
  buttons.py
  main.py
Labels: enhancement

#73 Features-C5-AddRolesJSON
  main.py
  roles.json
Labels: enhancement

#74 Features-B5-RuleskbmForAdmin
  buttons.py
  main.py
Labels: enhancement

#76 Features-B5-DelRulesFromUser
  main.py
Labels: enhancement

#77 Features-B5-ChekUserRules
  buttons.py
  main.py
Labels: enhancement

#79 Features-B5-CalendarButton
  main.py
Labels: enhancement

#81 Features-A5-EditAminPanel
  main.py
Labels: enhancement
